### ISSUE TITLE
Hoek dependency is deprecated

### ISSUE THREAD

**Issue by hugoluchessi** [launchdarkly/node-server-sdk#158]
**Describe the bug**
Hoek installation is warning with a deprecation warning.

**To reproduce**
Install this library with npm

**Expected behavior**
Not warning

**Logs**
```
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
```

**SDK version**
^5.9.0

**Language version, developer tools**
v10.16.0

**OS/platform**
Ubuntu 18.04

**Additional context**
-

**Comment by eli-darkly** [comment]
Hmm... at first glance it seems to me that our `hoek` dependency might be completely unused and obsolete. If so, we'll remove it; if not, we'll update it. Thanks for pointing this out.

**Comment by eli-darkly** [comment]
Removed this in the 5.9.2 release.
