### ISSUE TITLE
How to handle failure scenarios from launch darkly , 

### ISSUE THREAD

**Issue by Renukahuti** [launchdarkly/node-server-sdk#255]
What are the best strategies to handle failure scenarios so that our application can handle it without causing disruption .

1. When ever LD is down  or if we are unable to communicate with LD how to maintain the backup strategy to use flags 

2. Can use LD relay proxy for backup ?

**Comment by kinyoklion** [comment]
Hello @Renukahuti,

This question depends on your use case and the desired backup behavior you are after, and likely isn't specific to the node server SDK. Our Support Engineering Team is very knowledgeable and has more experience with customer deployments. Please submit this request through our [support channel](https://support.launchdarkly.com/hc/en-us). 

Thank you,
Ryan
