### ISSUE TITLE
Flushing %d events

### ISSUE THREAD

**Issue by tommoor** [launchdarkly/node-server-sdk#257]
**Describe the bug**
The SDK constantly prints "Flushing %d events" to the console.
<img width="187" alt="image" src="https://user-images.githubusercontent.com/380914/185151083-9c624689-aead-450f-a534-9c02d8ecae85.png">

**Expected behavior**
- Fix to properly interpolate the count, don't print anything if nothing was flushed, or just remove this altogether?

**Additional context**

https://github.com/launchdarkly/node-server-sdk/blob/7098956adb4ba466756d875fceccac8d63b24950/event_processor.js#L217

**Comment by kinyoklion** [comment]
Hello @tommoor, 

Are you using a custom logger with your SDK? The basic logger uses `line = util.format(...tempArgs);` to interpolate log lines.

Here is some output using the `basicLogger` provided with the SDK. Adjusted to show debug level items.
```
debug: [LaunchDarkly] Flushing 21 events
```

The creation of the logger:
```
  basicLogger({
    level: 'debug',
  });
```

You can also use the basic logger and change the destination.
```
basicLogger({
    level: 'debug',
    destination: line => {
      console.log(line);
    },
  });
```

If you are directly implementing the `LDLogger` interface, then it receives variadic arguments and you need to interpolate them.

The first of the args will be the format string, then any additional args.

```
    logger: {
      debug: (...args) => {
        console.log(...args);
      },
      info: (...args) => {
        console.log(...args);
      },
      warn: (...args) => {
        console.log(...args);
      },
      error: (...args) => {
        console.log(...args);
      },
    },
```

Produces:
```
Flushing 2 events
```

Thank you!
Ryan

**Comment by tommoor** [comment]
Thanks, looks like this is an issue with our implementation of the interface then 👍
