### ISSUE TITLE
Does your eventsource library override the native node version? 

### ISSUE THREAD

**Issue by xtianus79** [launchdarkly/node-server-sdk#262]
sorry I posted here but you can't use issues for that library that is forked. 

In this article the question talks about using a body. When I read your library it seems as if I have full control over the native eventsource from node. The only option is "withcredentials". Am I thinking of this correctly? 

I need to send information with my request. I'd like to do it in a post. Perhaps I am thinking of the wrong thing. Can you help explain this.

https://stackoverflow.com/questions/25099548/html-sse-request-body

**Comment by eli-darkly** [comment]
It's not totally clear to me what you're asking, so, a couple of clarifications:

1. The library you're talking about is https://github.com/launchdarkly/js-eventsource ... right?
2. When you say "full control over the native eventsource from Node", what do you mean by "the native eventsource"? The main reason that this library exists (which is the same reason that the original project we forked it from exists) is that there is no SSE/EventSource implementation built into Node. There is a native EventSource API _in web browsers_.
3. Did you read the README.md file? There's some fairly detailed documentation in it, including [this section](https://github.com/launchdarkly/js-eventsource#setting-http-request-methodbody) which is specifically about configuring it to do a POST request.
