### ISSUE TITLE
Logger configuration throws error 'Received put event'

### ISSUE THREAD

**Issue by apptrench** [launchdarkly/node-server-sdk#267]
**Describe the bug**
I am configuring logger when initializing LaunchDarkly in my node.js application. This is to avoid logs sent to console.error by default. After the configuration, I am observing an extra error log printed 'Received put event'

**To reproduce**
Configure LaunchDarkly by using the code - 
```
    const options: ld.LDOptions = {
      logger: {
        error: (...args: never[]) => console.error(...args),
        warn: (...args: never[]) => console.warn(...args),
        info: (...args: never[]) => console.info(...args),
        debug: (...args: never[]) => console.error(...args),
      },
    };

LaunchDarkly.init('sdk-key', options);
```

This prints the following log messages -
```
Initializing stream processor to receive feature flag updates
Opened LaunchDarkly stream connection
Received put event
```
**Expected behavior**
There should be two log statements -
```
Initializing stream processor to receive feature flag updates
Opened LaunchDarkly stream connection
```
**Logs**
If applicable, add any log output related to your problem.

**SDK version**
6.4.3

**Language version, developer tools**
Node.js with TypeScript

**OS/platform**
AWS Lambda

**Comment by kinyoklion** [comment]
Hello @apptrench, 

When using the default logger is is configured with a log level. Items below this level will not be logged. For instance the debugging level is used for debugging problems, and you generally would not want that level enabled, and it would not be enabled by default. You can either implement basic level support in your logger, or simply not log debug messages. It is also useful to tag the messages with the log level they were called with (the method name), so you can determine their origin. 

Thanks,
Ryan

**Comment by kinyoklion** [comment]
You can also use the basic logger itself, and change the destination.
```
ld.basicLogger({
  level: 'info' // the lowest level you want, the default basic logger uses 'info'.
  destination: <replaces console.error>
});
```

Some examples are here: https://github.com/launchdarkly/node-server-sdk/blob/0e810b90bbb3c759986b989df0518d7f4af10d84/index.d.ts#L1382

Thanks,
Ryan

**Comment by kinyoklion** [comment]
@apptrench Your sample code used console.error for the debug level.

**Comment by kinyoklion** [comment]
```
    const options: ld.LDOptions = {
      logger: {
        error: (...args: never[]) => console.error(...args),
        warn: (...args: never[]) => console.warn(...args),
        info: (...args: never[]) => console.info(...args),
        debug: (...args: never[]) => console.error(...args), // This line here.
      },
    };

LaunchDarkly.init('sdk-key', options);
```

**Comment by apptrench** [comment]
For now, this works for me - 
```
const options: ld.LDOptions = {
      logger: {
        error: (...args: never[]) => console.error(...args),
        warn: (...args: never[]) => console.warn(...args),
        info: (...args: never[]) => console.info(...args),
        debug: (...args: never[]) => {}, // This line here.
      },
    };

LaunchDarkly.init('sdk-key', options);
```
Thanks @kinyoklion
