### ISSUE TITLE
RedisFeatureStore: client.unref() causes AWS Lambda function to end unexpectedly

### ISSUE THREAD

**Issue by bnol** [launchdarkly/node-server-sdk#76]
Hi,

I'm using `RedisFeatureStore` with options `use_ldd: true` on AWS Lambda. Have an issue that the Lambda function ends unexpectedly.
Digging deeper into the SDK code, I found out that - after calling `client.unref();`
at https://github.com/launchdarkly/node-client/blob/master/redis_feature_store.js#L28
if I make any request to Redis after that it will cause the Lambda function to end unexpectedly (without calling the callback)

Can you please take a look at this issue?

**Comment by apucacao** [comment]
Hi @bnol ,

Thanks for reaching out.

Do you get any errors when the function exits?

**Comment by bnol** [comment]
Unfortunately, no @apucacao.

**Comment by bnol** [comment]
If I remove `client.unref();`. Everything works fine :)

**Comment by eli-darkly** [comment]
@bnol Apologies for having let this fall through the cracks. FYI, we are finally removing this unnecessary method call in the next SDK release.

**Comment by eli-darkly** [comment]
This is fixed in 5.13.1.
