### ISSUE TITLE
Unexpected token { in JSON at position XYZ

### ISSUE THREAD

**Issue by magne4000** [launchdarkly/node-server-sdk#82]
We have a lot of stacktraces like this one on an Electron project:
```
SyntaxError Unexpected token { in JSON at position 499 
    unknown parse
    node_modules/ldclient-node/streaming.js:25:26 none
    events.js:96:13 emitOne
    events.js:191:7 emit
    node_modules/ldclient-node/eventsource.js:193:17 _emit
    node_modules/ldclient-node/eventsource.js:207:9 parseEventStreamLine
    node_modules/ldclient-node/eventsource.js:170:11 none
    events.js:96:13 emitOne
    events.js:191:7 emit
    _stream_readable.js:178:18 readableAddChunk
    _stream_readable.js:136:10 push
    _http_common.js:123:22 parserOnBody
    _http_client.js:411:20 socketOnData
    events.js:96:13 emitOne
    events.js:191:7 emit
    _stream_readable.js:178:18 readableAddChunk
    _stream_readable.js:136:10 push
    net.js:560:20 onread [as _originalOnread]
    node_modules/async-listener/glue.js:188:31 onread
```

The position of the unexpected token (here 499) varies from client to client, but the error remains the same.
Any clue on what could go wrong, or how I can gather more details ?

**Comment by eli-darkly** [comment]
I forgot to say, it'd also be helpful to know the approximate date/time range when these messages occurred (not every one, just how long ago you first noticed them and whether they are still going on), in case it's correlated with any known service outage in the past.

**Comment by eli-darkly** [comment]
I've opened a support ticket for continued investigation - you should have received a link to it via email.

**Comment by magne4000** [comment]
In the end, after adding the debugging information, it was the following error that was triggering a lot:
`LaunchDarklyStreamingError: Connection closed, reconnecting`.
It's not really an error in our use case, so we just ignored it, but I think that it should be discussed on wether you should keep triggering this as an error or not.

**Comment by bwoskow-ld** [comment]
I'm going to close this issue as it has been inactive for over a year. However, before I do so, I wanted to mention that in the time since this issue was filed, we released a first-class Electron SDK. If you're currently using our Node Server SDK in an Electron application, we recommend considering switching over to it.

https://docs.launchdarkly.com/docs/electron-sdk-reference
